### ISSUE TITLE
show update download progress in an item non valid

### ISSUE THREAD

**Issue by godbout** [godbout/AlfredKat#13]
currently Alfred Kat sends a notification and starts the download, but Alfred itself disappear. it would be nice to keep Alfred open and show the progress of the download as a result item.

**Comment by godbout** [comment]
would need ScriptFilter rerun + launching a process in the background and somehow connect the background process to the rerun ScriptFilter (write progress in a cache file maybe?)

**Comment by xilopaint** [comment]
This would be a nice improvement. Hope to see this implemented any time soon.

**Comment by godbout** [comment]
i was gonna close this 😂️
with the latest version the download happens in the background, you can keep using Alfred or do some other stuff. download is super fast anyways. i'm busy with other things. definitely not a priority.

**Comment by godbout** [comment]
but i'm curious. how as a user do you see this being better than having the thing downloaded in the background quickly and you going do your stuff without thinking about it?

although the update opening once downloaded is a bit annoying hmm. could break your flow.

**Comment by godbout** [comment]
that requires a major work. not just for Alfred KAT. but more like a whole system to handle updates. i've spent a couple of days already improving the Updater. now much better. gonna be it for this year.

**Comment by xilopaint** [comment]
You don't need to keep Alfred open to provide the progress information. If your progress is written to a cache file you can provide the functionality through a keyword so users will only check the progress when they want. I've implemented this in my [Alfred PDF Tools](https://github.com/xilopaint/alfred-pdf-tools) workflow. In my case, I read stdout from my background process and write the progress to a cache file. When the user invokes the `progress` keyword a script filter with rerun is started.

**Comment by godbout** [comment]
yeah, true. but how often do you thing this is used?

**Comment by godbout** [comment]
does your workflow launch the update once downloaded too? or do you have a smarter system?

**Comment by xilopaint** [comment]
Oh gosh! I'm sorry! I think I misunderstood what this issue was about. Now I see it's about the  "*UPDATE* download progress".  For a moment I thought it was about files we download using the workflow.

**Comment by godbout** [comment]
OOOOOOOOOHHHHHHH LMAO. now your comments make a lot of sense 😂️😂️😂️

i never thought about showing the progress of the torrents in Alfred. hence the confusion. the title of the issue and the rest of my words are definitely confusing.

**Comment by godbout** [comment]
not even sure how it would be possible to do that with the torrents. i mean i'm not the one "downloading" them. i don't have any clean access to that info. reading the .part files? that'd be crazy. i mean maybe there's a way, but definitely not something i'm interested in implementing. although it would look super cool and probably would get me some dates with the ladies.

**Comment by xilopaint** [comment]
> not even sure how it would be possible to do that with the torrents.

Maybe reading stdout from transmission-cli?

**Comment by godbout** [comment]
> Maybe reading stdout from transmission-cli?

that was my first thought but i had to pull myself out of my own world and remind myself that Alfred KAT is client agnostic 😅️

i mean sure, for PRO users you can set your own client and i could grab that. but each client would have its own format so yeah so no.

**Comment by xilopaint** [comment]
Yeah, maybe not worth it.

**Comment by godbout** [comment]
i could show an Alfred Result telling users to go see in their torrent client aww 😍️
