### ISSUE TITLE
404 error on any and all searches

### ISSUE THREAD

**Issue by yourmomdatestedcruz** [godbout/AlfredKat#15]
I keep getting 404 errors on any search I try. I've attempted to change the URL in the variables but not luck.

Alfred version: 4.6.6
MacOS 12.2.1 Monterey
Tried versions 7.0.0 and 6.2.0; no luck either

Let me know if you need more info to diagnose

**Comment by godbout** [comment]
i need the debug info coming from Alfred's console. thanks.

**Comment by yourmomdatestedcruz** [comment]
Never-mind a restart fixed it. I'll come back to this if it happens again, and provide the debug info.

**Comment by godbout** [comment]
a good sleep always helps. closing for now. reopen if you're having the issue again.

**Comment by yourmomdatestedcruz** [comment]
Heyo again, i ran into it again, i pasted the log below (running the workflow as "kat test") - let me know if you want me to run something specific.

[22:38:03.603] Kickass Torrents[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.09337DC5-1523-446C-B309-696F720242A8%3E2FC960F6-0D18-4D56-AD7A-7C083013B843)] Queuing argument 'te'
[22:38:03.893] Kickass Torrents[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.09337DC5-1523-446C-B309-696F720242A8%3E2FC960F6-0D18-4D56-AD7A-7C083013B843)] Queuing argument 'test'
[22:38:04.624] Kickass Torrents[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.09337DC5-1523-446C-B309-696F720242A8%3E2FC960F6-0D18-4D56-AD7A-7C083013B843)] Script with argv 'test' finished
[22:38:04.629] Kickass Torrents[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.09337DC5-1523-446C-B309-696F720242A8%3E2FC960F6-0D18-4D56-AD7A-7C083013B843)] {"items":[{"title":"404 for test ☹️","subtitle":"try some other terms maybe?"}]}

**Comment by godbout** [comment]
1. what's in the `url` variable for the Workflow?
2. what happens if you open that `url` in a browser?
3. you're behind any firewall? school wifi? work wifi? parental controls?

**Comment by yourmomdatestedcruz** [comment]
It seems to be working again, love intermittent faults....

To answer your questions:

1. the url is: https://kickasstorrents.to
2. I get to the website fine, no long wait, no browser check, no captcha, no nothing. 
3. I'm not behind any firewall, I do have a pi-hole server (i've checked and it's not blocking anything related as far as I can tell), and a VPN.

Next time it happens, i'll troubleshoot a bit, try to deactivate pi-hole and my VPN see if that helps? I'll also check that the URL still gets me to the website - it may be periodically inaccessible? and let you know what I find.

Thanks for your help!

**Comment by godbout** [comment]
> It seems to be working again, love intermittent faults....

that's how i build my software yeah. personal touch 👌️

> To answer your questions:
> 
> 1. the url is: https://kickasstorrents.to
> 2. I get to the website fine, no long wait, no browser check, no captcha, no nothing.

the site need to be checked when KAT doesn't work. maybe it's down, ISP doing something, nor just the site not returning results. not sure.

> 3. I'm not behind any firewall, I do have a pi-hole server (i've checked and it's not blocking anything related as far as I can tell), and a VPN.

this is what you get if KAT can't reach the Internet:

![Screen Shot 2022-06-13 at 19 45 32](https://user-images.githubusercontent.com/121373/173346876-353e7ee6-2855-47e7-a9a1-4f78104f708b.png)

so the 404 for your case means it's able to go out. but why he can't get results? honestly no idea. could be a million stuff. bad caching through your pi. maybe VPN adding stuff on the page that wrecks the HTML? what KAT does behind the scenes if grabbing the HTML returned by the site and parsing it. the site has no API to fetch results.

> Next time it happens, i'll troubleshoot a bit, try to deactivate pi-hole and my VPN see if that helps? I'll also check that the URL still gets me to the website - it may be periodically inaccessible? and let you know what I find.

yeah i think at least, check the site when KAT doesn't work. then save the page and upload it here. maybe the HTML is different from what KAT expects. could be something injecting stuff on the page. could be depending on where you're located (through the VPN). there's quite a few users of KAT and didn't have any report. i use it myself daily and no issues. but in any case it's open source so maybe you may to open it and do some heart surgery for yourself :D

**Comment by yourmomdatestedcruz** [comment]
Ok thanks for your help! I'll check the page when KAT doesn't work and see if I find anything.

> open it and do some heart surgery for yourself :D

Yeeaaaah see you assume i might know how to hold a scalpel here.... you'd be very wrong

------------------------------------------

Completely unrelated, how could I customize the results of a search? change the order that the info is displayed in, put the title of the torrent in the title and the info in the sub title.... that kind of thing? is that also open heart surgery/brain science or is it simpler?

**Comment by godbout** [comment]
> Completely unrelated, how could I customize the results of a search? change the order that the info is displayed in, put the title of the torrent in the title and the info in the sub title.... that kind of thing? is that also open heart surgery/brain science or is it simpler?

for that you just need a PhD in neuroscience yes. 

the only options are what's stated in the README (https://github.com/godbout/AlfredKat#what-is-that): `^` to sort (maybe only `^seeders` work. don't remember. no time to check) and `#` for tags (that one works with several for sure, like `#music`, `#video(s?)` etc.)

the way i build software in general is: 1) i build for myself 2) i build for today's needs. for paid apps i take users' suggestions and implement them if it makes the app better. that's also true for OSS actually, but depends on time/priorities. currently i have no time and a lot of priorities.

i'd suggest:
* or learn open heart surgery, fork KAT, implement a possible config. i'll take a PR and merge, if it has automated tests
* or find someone who can/want to do that
* or pay someone who doesn't want to do that but loves money

good luck!
