### ISSUE TITLE
[Feature Request] Use the Configuration Builder instead of Environment Variables' sheet

### ISSUE THREAD

**Issue by xilopaint** [godbout/AlfredKat#16]
More info on https://www.alfredapp.com/help/workflows/workflow-configuration/

**Comment by godbout** [comment]
will review. thanks.

**Comment by godbout** [comment]
@xilopaint what your reason for using the Configuration Builder over the Environment Variables? if it's regarding the `url`, i don't want to expose this to users through the Configuration Builder. the `url` is just there in case the site is temporarily down, but it's not done for users to type up any site they want (see https://github.com/godbout/AlfredKat/issues/17). so it's more like a "just in case". if you're talking about for the [pro users](https://github.com/godbout/AlfredKat#pro-users) thing, i haven't thought that much about it yet coz it's late here 😂️😂️😂️

**Comment by xilopaint** [comment]
> @xilopaint what your reason for using the Configuration Builder over the Environment Variables? if it's regarding the `url`, i don't want to expose this to users through the Configuration Builder. the `url` is just there in case the site is temporarily down, but it's not done for users to type up any site they want (see #17). so it's more like a "just in case". if you're talking about for the [pro users](https://github.com/godbout/AlfredKat#pro-users) thing, i haven't thought that much about it yet coz it's late here 😂️😂️😂️

As far as I know the Environment Variables section is only maintained for backwards compatibility. One of requisites for a workflow being submitted to Alfred Gallery, for example, is always using User Configuration instead of Environment Variables. If the `url` is used only in case the website is down, you can indicate this in a description. So, I think both `url` and `cli` should be part of User Configuration with proper descriptions.

**Comment by xilopaint** [comment]
> @xilopaint what your reason for using the Configuration Builder over the Environment Variables? if it's regarding the `url`, i don't want to expose this to users through the Configuration Builder. the `url` is just there in case the site is temporarily down, but it's not done for users to type up any site they want (see #17). so it's more like a "just in case". if you're talking about for the [pro users](https://github.com/godbout/AlfredKat#pro-users) thing, i haven't thought that much about it yet coz it's late here 😂️😂️😂️

As far as I know the Environment Variables section is only maintained for backwards compatibility. One of requisites for a workflow being submitted to Alfred Gallery, for example, is always using User Configuration instead of Environment Variables. If the `url` is used only in case the website is down, you can indicate this in a description. So, I think both `url` and `cli` should be part of User Configuration with proper descriptions.

**Comment by godbout** [comment]
> As far as I know the Environment Variables section is only maintained for backwards compatibility. One of requisites for a workflow being submitted to Alfred Gallery, for example, is always using User Configuration instead of Environment Variables. If the `url` is used only in case the website is down, you can indicate this in a description. So, I think both `url` and `cli` should be part of User Configuration with proper descriptions.

well i was planning to start putting my Workflows in the Gallery but then use an Environment Variable for the Updater. that's a requisite of the Updater, now that GitHub has changed the way they load assets. the developer of a Workflow will have to add an Environment Variable, but this shouldn't be touched by the end user of the Workflow. so yeah, it made sense to me that both the User Configuration and the Environment Variables exist. they'd be there for different reasons. if actually things need to be all transferred to User Configuration, that's just plain weird to me. gonna squeeze what developers can do safely. so i guess yeah, no Gallery for me.

**Comment by xilopaint** [comment]
Gallery workflows can't have built-in updaters as well as they're updated by its own mechanism. Regarding the `url`, I just can't understand your point. If you think it shouldn't be touched by the end user why don't you hard code it in the first place? The Environment Variable section was created to expose the variables to end users, but Alfred 5 introduced a more comprehensive and user-friendly interface that should be preferred which is User Configuration.

**Comment by godbout** [comment]
> Gallery workflows can't have built-in updaters as well as they're updated by its own mechanism. 

yeah, i'm seeing the list of constraints. curated by Vitor. so obviously my stuff will never be allowed there 😂️😂️😂️

> Regarding the `url`, I just can't understand your point. If you think it shouldn't be touched by the end user why don't you hard code it in the first place? The Environment Variable section was created to expose the variables to end users, but Alfred 5 introduced a more comprehensive and user-friendly interface that should be preferred which is User Configuration.

i firstly build stuff for myself. when the original site is down, i can quickly change it in the variable and make KAT works through a temporary change, rather than shitting a new build. i don't think it's crazy to think that Workflows need a set of configuration variables for end users, and one for maybe developers. one set where the end users is expected to set his data, like API keys, and another for stuff that shouldn't be changed, but can if needed.
